---
title: "Dzień 1 - Sprawy organizacyne"
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---
<style type="text/css">
.title {
  display: none;
}

.table {
    width:70%;
}

#getting-started img {
  margin-right: 10px;
}

</style>



# Sprawy organizacyjne

* Liczba godzin: 10 godz. (ćwiczenia).
* Liczba punktów ECTS: 1.
* Forma zaliczenia: zaliczenie na ocenę.
* Konsultacje: terminy i maile na stronie w domenie WMiI - [link](http://wmii.uwm.edu.pl/~piojas/).

## Treści zajęć

Ćwiczenia:

* Metody prezentacji danych statystycznych
* Zalety i ograniczenia rozmaitych technik prezentacji
* Istota i cel tworzenia raportów
* Techniki prezentacji danych jednowymiarowych
* Techniki prezentacji danych wielowymiarowych


## Forma i warunki weryfikacji efektów

Ćwiczenia: 

* mini-projekt, 
* aktywność na zajęciach.


## Literatura

* Walesiak M., Gatnar E., Statystyczna analiza danych z wykorzystaniem programu R, PWN, Warszawa, 2009.
* Wasilewska E., Statystyka opisowa od podstaw, Podręcznik z zadaniami, Wydawnictwo SGGW, Warszawa, 2009.
* Larose Daniel T., Metody i modele eksploracji danych, PWN, Warszawa, 2008.
* P. Biecek, Przewodnik po pakiecie R, Oficyna Wydawnicza GiS, 2017.
* https://rstudio-pubs-static.s3.amazonaws.com/7953_4e3efd5b9415444ca065b1167862c349.html
* https://www.harding.edu/fmccown/r/
* http://www.melissaclarkson.com/resources/R_guides/documents/figure_layout_Ver1.pdf
* http://www.sthda.com/english/wiki/add-legends-to-plots-in-r-software-the-easiest-way


