---
title: "Dzień 3 - wykresy wielowymiarowe"
output:
  html_document:
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---
<style type="text/css">
.title {
  display: none;
}

.table {
    width:70%;
}

#getting-started img {
  margin-right: 10px;
}

</style>



# Wykresy wielowymiarowe

## Wykres punktowy dla trzech zmiennych

Uwaga: warto zwrócić uwagę na parametry kolorów. 

```{r}
library(MASS)
head(ships)
plot(ships$incidents,ships$service,col=ships$type, pch=16)
legend("topleft",legend = levels(ships$type), col = c(1:5), pch=16)
```

## Baza `iris`

```{r}
data(iris)
head(iris)
plot(iris$Sepal.Length, iris$Petal.Length, col = iris$Species)
plot(iris$Sepal.Length, iris$Petal.Length, col = iris$Species, pch = 16)
plot(iris$Sepal.Length, iris$Petal.Length,
     col = iris$Species,
     pch = 16,
     cex = 2)
legend(x = 4.5, y = 7, legend = levels(iris$Species), col = c(1:3), pch = 16)
pairs(iris)
```

## Wykres mozaikowy

W tym typie wykresu podtrzebujemy zwykle macierzy/tabeli.
```{r}
choroby<-matrix(c(34,12,22,18),ncol=2,byrow=TRUE)
colnames(choroby) <- c("M","K")
rownames(choroby)<- c("GDO", "DDO")
mosaicplot(choroby, color = rainbow(2))
```

```{r}
mosaicplot(HairEyeColor, col=heat.colors(2))
```

## Wykres w perspektywie

```{r}
x <- seq(-10, 10, length = 30) 
y <- x  
f <- function(x, y) {r <- sqrt(x ^ 2 + y ^ 2); 10 * sin(r) / r}
z <- outer(x, y, f) 
persp(x, y, z)
```